### ISSUE TITLE
No parallel

### ISSUE THREAD

**Issue by biostat0903** [wavefancy/WallaceBroad#1]
Hi, 
It is great for you to modify the code of LDpred. Today , I have try your code and find some problems. 
1. I cannot use the "parallel" package of the cluster. I do not know whether the code work without parallel package. 
2. I run "coord_genotype" by the code (without parallel):
````
coord_genotypes.py --gf=mypath/EUR_chr{} --N=28950 --ssf=mypath/pheno${PHENO}_chr{}.summStd --ssf_format=BASIC --out mypath/coord.file.chr{}
`````
Summary data is 
````
hb19chrc snpid a1 a2 bp or p
chr22 22:16495833 A C 16495833 1.00131 0.498793
chr22 22:16496170 A G 16496170 1.00131 0.498793
chr22 22:16869617 G A 16869617 1.0044 0.0226932
````
The error is:
````
command not found
import: unable to open X server `localhost:31.0' @ error/import.c/ImportImageCommand/364.
import: unable to open X server `localhost:31.0' @ error/import.c/ImportImageCommand/364.
import: unable to open X server `localhost:31.0' @ error/import.c/ImportImageCommand/364.
import: unable to open X server `localhost:31.0' @ error/import.c/ImportImageCommand/364.
import: unable to open X server `localhost:31.0' @ error/import.c/ImportImageCommand/364.
import: unable to open X server `localhost:31.0' @ error/import.c/ImportImageCommand/364.
from: too many arguments
from: too many arguments
import: unable to open X server `localhost:31.0' @ error/import.c/ImportImageCommand/364.
/usr/cluster/bin/coord_genotypes.py: line 53: syntax error near unexpected token `('
/usr/cluster/bin/coord_genotypes.py: line 53: `ambig_nts = set([('A', 'T'), ('T', 'A'), ('G', 'C'), ('C', 'G')])'

````

**Comment by wavefancy** [comment]
Hi,
It's not a necessity to use parallel. I just use parallel to control the loop. You can use bash for-loop to replace it. 

2. What the output if you run ```coord_genotypes.py -h```?  Can you get the output successfully? If not. It's better to try:
```
python2 $PATH_TO/coord_genotypes.py
```
 $PATH_TO is the full path to have your ```coord_genotypes.py```.

My example is like:
```
python2 /medpop/esp2/wallace/tools/miniconda3/envs/Python27/lib/python2.7/site-packages/ldpred/coord_genotypes.py -h 
```

**Comment by biostat0903** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hi, 
        I try to use the code without parallel. But there are still some errors. My code:PHENO=1COORPY=/net/mulan/home/yasheng/miniconda2/lib/python2.7/site-packages/ldpred/coord_genotypes.py REF=/net/fantasia/home/xzhousph/data/SummaryData/1000GP_Phase3/processed/EUR_chr{}SUMM=/net/mulan/home/yasheng/Biobank/data/summaryData/pheno${PHENO}/ldpred/pheno${PHENO}_chr{}.summStd OUTPUT=/net/mulan/home/yasheng/Biobank/result/ldpred/coord.file.chr{}for((i=1;i<=22;i++)){${COORPY} --gf= ${REF} --N=268950 --ssf=${SUMM} --ssf_format=BASIC --out ${OUTPUT}}error:Traceback (most recent call last):  File "/net/mulan/home/yasheng/miniconda2/lib/python2.7/site-packages/ldpred/coord_genotypes.py", line 1836, in <module>    main()  File "/net/mulan/home/yasheng/miniconda2/lib/python2.7/site-packages/ldpred/coord_genotypes.py", line 1797, in main    if os.path.isfile(p_dict['out']):  File "/net/mulan/home/yasheng/miniconda2/lib/python2.7/genericpath.py", line 37, in isfile    st = os.stat(path)TypeError: coercing to Unicode: need string or buffer, NoneType foundThanks for your help!
    
        
            
        
    Best,
    
         
        
            
    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    
Sheng YangPh.D, Postdoctral fellowCenter for Statistical Genetics in Department of BiostatisticsUniversity of MichiganDepartment of BiostatisticsNanjing Medical University



        
    
     

    On 10/5/2018 15:49，wavefancy<notifications@github.com> wrote： 


Hi,
It's not a necessity to use parallel. I just use parallel to control the loop. You can use bash for-loop to replace it.

What the output if you run coord_genotypes.py -h?  Can you get the output successfully? If not. It's better to try:

python2 $PATH_TO/coord_genotypes.py

$PATH_TO if the full path to have your coord_genotypes.py.
My example is like:
/medpop/esp2/wallace/tools/miniconda3/envs/Python27/lib/python2.7/site-packages/ldpred/coord_genotypes.py

**Comment by wavefancy** [comment]
Does this because your file name contains '{}'? 

Can you try this? Just run chr1 as a test example?
```
python2 /net/mulan/home/yasheng/miniconda2/lib/python2.7/site-packages/ldpred/coord_genotypes.py \
--gf=/net/fantasia/home/xzhousph/data/SummaryData/1000GP_Phase3/processed/EUR_chr1 \
--N=268950 \
--ssf=/net/mulan/home/yasheng/Biobank/data/summaryData/pheno${PHENO}/ldpred/pheno${PHENO}_chr1.summStd  \
--ssf_format=BASIC \
--out /net/mulan/home/yasheng/Biobank/result/ldpred/coord.file.chr1
```

Sorry, I used '{}' as I used gnu 'parallel' for control for-loop. The parallel will convert {} to chr name actually. 

Best
Wallace

**Comment by biostat0903** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hi, 
        I run the code . And get the same error as the last email. 
    
        
            
        
    Best,
    
         
        
            
    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    
Sheng YangPh.D, Postdoctral fellowCenter for Statistical Genetics in Department of BiostatisticsUniversity of MichiganDepartment of BiostatisticsNanjing Medical University



        
    
     

    On 10/8/2018 17:13，wavefancy<notifications@github.com> wrote： 


Does this because your file name contains '{}'?
Can you try this? Just run chr1 as a test example?
python2 /net/mulan/home/yasheng/miniconda2/lib/python2.7/site-packages/ldpred/coord_genotypes.py \
--gf= /net/fantasia/home/xzhousph/data/SummaryData/1000GP_Phase3/processed/EUR_chr1 \
--N=268950 \
--ssf=/net/mulan/home/yasheng/Biobank/data/summaryData/pheno${PHENO}/ldpred/pheno${PHENO}_chr1.summStd  \
--ssf_format=BASIC \
--out /net/mulan/home/yasheng/Biobank/result/ldpred/coord.file.chr1

Sorry, I used '{}' as I used gnu 'parallel' for control for-loop. The parallel will convert {} to chr name actually.
Best
Wallace

**Comment by wavefancy** [comment]
hmm.... it's weird.

Can you show me what's your output?

Does your output folder really exit? 
What does the output of 
```
ls /net/mulan/home/yasheng/Biobank/result/ldpred/
```

**Comment by biostat0903** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hi, 
        I do not have any output. And I set the output directory as the root directory. But still have the error. 
    
        
            
        
    Best,
    
         
        
            
    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    
Sheng YangPh.D, Postdoctral fellowCenter for Statistical Genetics in Department of BiostatisticsUniversity of MichiganDepartment of BiostatisticsNanjing Medical University



        
    
     

    On 10/8/2018 17:41，wavefancy<notifications@github.com> wrote： 


hmm.... it's weird.
Can you show me what's your output?
Does your output folder really exit?
What does the output of
ls /net/mulan/home/yasheng/Biobank/result/ldpred/
