### ISSUE TITLE
need chromosome list from coordinate_genotypes.py

### ISSUE THREAD

**Issue by yingji15** [wavefancy/WallaceBroad#3]
Hi Wallace,
Thanks for your amazing efforts in separating this into chromosomes!
I am a python beginner, but I feel there is a minor issue: in the new coordinate_genotypes.py. the following part that define chromosomes_list is missing, so i got errors when import this later in LDpred.ScaleEffectSize.CHR.Numpy.Wallace.V1.py. After adding this back, it seems fine.

This is the part missing in coordinate_genotypes.py

#LDpred currently ignores the Y and MT chromosomes.
ok_chromosomes = ['%d' % (x) for x in range(1, 23)]
ok_chromosomes.append('X')
chromosomes_list = ['chrom_%s' % (chrom) for chrom in ok_chromosomes]

**Comment by wavefancy** [comment]
Hi Ying,

Which version are you using? The one from github is not compatible with the
chr by chr version. You may need the one from pip.

Best regards,
Wallace

**Comment by yingji15** [comment]
Hi Wallace,
I used the one from this repository and it seems to work well after adding the 3 lines. I haven't look at the the version on pip but I will check that. Thanks!

Ying
